// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Task4Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void task4() {
    driver.Navigate().GoToUrl("https://client.sana-commerce.dev//petclinic/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) > a")).Click();
    driver.FindElement(By.XPath("/html/body/app-root/app-owner-list/div/div/div/table/tbody/tr[1]/td[1]/a")).Click();
    driver.FindElement(By.CssSelector(".addNewPet")).Click();
    driver.FindElement(By.Id("name")).Click();
    driver.FindElement(By.Id("name")).SendKeys("lkmnbvc");
    driver.FindElement(By.CssSelector(".mat-datepicker-toggle-default-icon")).Click();
    driver.FindElement(By.CssSelector(".mat-calendar-period-button")).Click();
    driver.FindElement(By.CssSelector(".ng-star-inserted:nth-child(6) > .mat-calendar-body-cell:nth-child(4) > .mat-calendar-body-cell-content")).Click();
    driver.FindElement(By.CssSelector(".ng-star-inserted:nth-child(4) > .mat-calendar-body-cell:nth-child(4) > .mat-calendar-body-cell-content")).Click();
    driver.FindElement(By.CssSelector(".mat-calendar-body-active > .mat-calendar-body-cell-content")).Click();
    driver.FindElement(By.Id("type")).Click();
    {
      var dropdown = driver.FindElement(By.Id("type"));
      dropdown.FindElement(By.XPath("//option[. = 'Akita']")).Click();
    }
    driver.FindElement(By.CssSelector(".savePet")).Click();
    driver.Close();
  }
}
